Fix: use GLPI core console for locale extraction

diff --git a/.github/workflows/transifex-sync.yml b/.github/workflows/transifex-sync.yml
--- a/.github/workflows/transifex-sync.yml
+++ b/.github/workflows/transifex-sync.yml
@@ -12,27 +12,44 @@ jobs:
   transifex-sync:
     name: "Sync locales with Transifex"
     runs-on: "ubuntu-latest"
+    container:
+      image: "ghcr.io/glpi-project/githubactions-glpi-apache:latest"
+      options: --user 1001 # using built-in image user, otherwise GitHub Actions can't write file to the container
+
     steps:
-
-    - name: "Checkout"
+    - name: "Checkout setup.php"
       uses: "actions/checkout@v7"
-
-    - name: "Install system dependencies"
-      run: |
-        sudo apt-get update --quiet
-        sudo apt-get install gettext libgettextpo-dev python3-dev python3-pip libffi-dev libxml2-dev libxslt-dev git
-        pip install lxml gitpython PyGithub termcolor
-
-    - name: "Install composer dependencies"
-      uses: "php-actions/composer@v6"
       with:
-        dev: yes
+        sparse-checkout: setup.php
+        path: tmp_setup
+
+    - name: "Get Plugin Key"
+      run: |
+        PLUGIN_KEY=$(sed --quiet 's/.*function plugin_version_\([a-z0-9_]\+\).*/\1/p' tmp_setup/setup.php | head --lines=1)
+        if [ -z "$PLUGIN_KEY" ]; then
+          echo "Could not extract plugin key from setup.php"
+          exit 1
+        fi
+        echo "PLUGIN_KEY=$PLUGIN_KEY" >> $GITHUB_ENV
+
+    - name: "Checkout Plugin"
+      uses: "actions/checkout@v7"
+      with:
+        path: "plugins/${{ env.PLUGIN_KEY }}"
+
+    - name: "Link Plugin to GLPI"
+      run: |
+        sudo ln -s "$GITHUB_WORKSPACE/plugins/$PLUGIN_KEY" "/var/www/glpi/plugins/$PLUGIN_KEY"
+        sudo chmod -R a+rwX /var/www/glpi/
+        git config --global --add safe.directory '*'
 
     - name: "Extract locales"
+      working-directory: "/var/www/glpi/"
       run: |
-        ./vendor/bin/extract-locales
+        php bin/console tools:locales:extract --plugin=${{ env.PLUGIN_KEY }} --no-interaction
 
     - name: "Push source file"
+      working-directory: "plugins/${{ env.PLUGIN_KEY }}"
       uses: "transifex/cli-action@v2"
       with:
         args: "push"
@@ -43,18 +60,21 @@ jobs:
         rm -fr /tmp/tx
 
     - name: "Pull translations"
+      working-directory: "plugins/${{ env.PLUGIN_KEY }}"
       uses: "transifex/cli-action@v2"
       with:
         args: "pull --force --all --minimum-perc=80"
         token: "${{ secrets.transifex-token }}"
 
     - name: "Compile MO files"
+      working-directory: "/var/www/glpi/"
       run: |
-        ./vendor/bin/plugin-release --compile-mo
+        php bin/console tools:locales:compile --plugin=${{ env.PLUGIN_KEY }} --no-interaction
 
     - name: "Check status"
       id: "check-status"
-      # en_GB.mo file will always be considered as updated as it is regenerated by the ./vendor/bin/extract-locales command.
+      working-directory: "plugins/${{ env.PLUGIN_KEY }}"
+      # en_GB.mo file will always be considered as updated as it is regenerated by the extract-locales command.
       # It have to be ignore to prevent "empty" PRs to be generated.
       run: |
         if [[ `git status --porcelain locales/*.mo ':(exclude)locales/en_GB.mo'` ]]; then
@@ -67,6 +87,7 @@ jobs:
       if: ${{ steps.check-status.outputs.CREATE_PR == 'yes' }}
       uses: "peter-evans/create-pull-request@v8"
       with:
+        path: "plugins/${{ env.PLUGIN_KEY }}"
         commit-message: "Update locales"
         branch: "i18n-updates"
         branch-suffix: "timestamp"
